### ISSUE TITLE
Use of plt.figure()

### ISSUE THREAD

**Issue by davidgasquez** [rhiever/python-data-visualization-course#3]
I can see `plt.figure()` in each cell with a plot but I think this is not needed while using **pyplot**.

**Comment by rhiever** [comment]
That's correct that `plt.figure()` is not required with pyplot, especially in the IPython Notebook. However, since this is a training course, the goal is to get the users into the habit of calling `plt.figure()` every time they want to create a figure. Furthermore, the `plt.figure()` call has many useful parameters that the users can take advantage of, such as changing the figure size.

**Comment by davidgasquez** [comment]
Thanks for the elaborated reply! I'll be looking forward this awesome course.
